import {
  Cards,
  CardTransactionModel,
  HeaderModel,
} from "app/shared/models/card.model";
import { TableHeader } from "../../dashboard/modules/cheque-book/cheque.store";
import { QuickLinkTabModel, TabModel } from "app/shared/models/tab-model";

export class CreditCardStore {
  static readonly serviceTabs: TabModel[] = [
    {
      screenName: "Card Dashboard",
      route: "/card/credit-card",
      src: "assets/images/send-money-icon.svg",
      selectedSrc: "assets/images/send-money-unselected.svg",
      icon: "send-money-icon",
      selectedIcon: "send-money-unselected",
    },
    {
      screenName: "Payment",
      route: "/card/credit-card/service/payment",
      src: "assets/images/card-payment-blue.svg",
      selectedSrc: "assets/images/card-payment-white.svg",
      icon: "card-payment-blue",
      selectedIcon: "card-payment-white",
    },
    {
      screenName: "Convert to EMI",
      route: "/card/credit-card/service/convert-to-emi",
      src: "assets/images/net-banking/loans/loan-repayment.svg",
      selectedSrc: "assets/images/selected-quick-transfer.svg",
      icon: "loan_repayment",
      selectedIcon: "selected-payment-icon",
    },
    {
      screenName: "Card Summary",
      route: "/card/credit-card/service/card-summary",
      src: "assets/images/card-summary-blue.svg",
      selectedSrc: "assets/images/card-summary-white.svg",
      icon: "card-summary-icon",
      selectedIcon: "selected-card-summary-icon",
    },
    {
      screenName: "AutoPay",
      route: "/card/credit-card/service/autopay",
      src: "assets/images/auto-debit-blue.svg",
      selectedSrc: "assets/images/auto-debit-white.svg",
      icon: "autopay-icon",
      selectedIcon: "selected-autopay-icon",
    },
    {
      screenName: "Billing Cycle",
      route: "/card/credit-card/service/billing-cycle",
      src: "assets/images/billing-cycle-blue.svg",
      selectedSrc: "assets/images/billing-cycle-white.svg",
      icon: "bill-cycle-icon",
      selectedIcon: "selected-bill-cycle-icon",
    },
    {
      screenName: "E Statement",
      route: "/card/credit-card/service/e-statement",
      src: "assets/images/e-statment-blue.svg",
      selectedSrc: "assets/images/e-statment-white.svg",
      icon: "bill-cycle-icon",
      selectedIcon: "selected-bill-cycle-icon",
    },
    {
      screenName: "PIN Generation",
      route: "/card/credit-card/service/pin-generation",
      src: "assets/images/pin-generation-blue.svg",
      selectedSrc: "assets/images/pin-generation-white.svg",
      icon: "pin-gen-icon",
      selectedIcon: "selected-pin-gen-icon",
    },
    {
      screenName: "Block Card",
      route: "/card/credit-card/service/block-card",
      src: "assets/images/block-card-blue.svg",
      selectedSrc: "assets/images/block-card-white.svg",
      icon: "block-card-icon",
      selectedIcon: "selected-block-card-icon",
    },
    {
      screenName: "Change PIN",
      route: "/card/credit-card/service/change-pin",
      src: "assets/images/change-pin-blue.svg",
      selectedSrc: "assets/images/change-pin-white.svg",
      icon: "change-pin-icon",
      selectedIcon: "selected-change-pin-icon",
      skipActionButton: true,
    },
    {
      screenName: "Card EMI Details",
      route: "/card/credit-card/service/card-emi-details",
      src: "assets/images/emi-details-blue.svg",
      selectedSrc: "assets/images/emi-details-white.svg",
      icon: "emi-details-icon",
      selectedIcon: "selected-emi-details-icon",
    },
    {
      screenName: "Pre Generated Statement",
      route: "/card/credit-card/service/pre-generated-statement",
      src: "assets/images/pre-generated-blue.svg",
      selectedSrc: "assets/images/pre-generated-white.svg",
      icon: "payment-icon",
      selectedIcon: "selected-payment-icon",
    },
    {
      screenName: "Insta Loan",
      route: "/card/credit-card/service/instant-loan",
      src: "assets/images/insta-loan-blue.svg",
      selectedSrc: "assets/images/insta-loan-white.svg",
      icon: "insta-loan-icon",
      selectedIcon: "selected-insta-loan-icon",
    },
    {
      screenName: "Alert Subscription",
      route: "/card/credit-card/service/alert-subscription",
      src: "assets/images/alert-sub-blue.svg",
      selectedSrc: "assets/images/alert-sub-white.svg",
      icon: "alert-subsc-icon",
      selectedIcon: "selected-alert-subsc-icon",
    },
    {
      screenName: "Unbilled Transaction",
      route: "/card/credit-card/service/unbilled-transaction",
      src: "assets/images/unbilled-transcation-blue.svg",
      selectedSrc: "assets/images/unbilled-transcation-white.svg",
      icon: "unbill-trans-icon",
      selectedIcon: "selected-unbill-trans-icon",
    },
    {
      screenName: "Add On Card",
      route: "/card/credit-card/service/add-on-card",
      src: "assets/images/addcard-blue.svg",
      selectedSrc: "assets/images/addcard-white.svg",
      icon: "add-card-icon",
      selectedIcon: "selected-add-card-icon",
    },
    {
      screenName: "Upgrade",
      route: "/card/credit-card/service/upgrade",
      src: "assets/images/upgrade-white.svg",
      selectedSrc: "assets/images/upgrade-blue.svg",
      icon: "upgrade-icon",
      selectedIcon: "selected-upgrade-icon",
    },
  ];
  static readonly manageCardTabs: TabModel[] = [
    {
      screenName: "Card Control",
      route: "/card/credit-card/manage/card-control",
      src: "assets/images/card-control-icon.svg",
      selectedSrc: "assets/images/selected-card-control-icon.svg",
      icon: "card-control-icon",
      selectedIcon: "selected-card-control-icon",
    },
    {
      screenName: "Usage Limit",
      route: "/card/credit-card/manage/card-usage",
      src: "assets/images/selected-usage-limit-icon.svg",
      selectedSrc: "assets/images/selected-usage-limit-icon.svg",
      icon: "selected-usage-limit-icon",
      selectedIcon: "selected-usage-limit-icon",
    },
  ];

  static readonly applyTabs: TabModel[] = [
    {
      screenName: "Apply Card",
      route: "/card/credit-card/manage/card-control",
      src: "assets/images/svg/card-icons/card-control-icon.svg",
      selectedSrc:
        "assets/images/svg/card-icons/selected-card-control-icon.svg",
      icon: "card-control-icon",
      selectedIcon: "selected-card-control-icon",
    },
    {
      screenName: "Tracking",
      route: "/card/credit-card/manage/card-usage",
      src: "assets/images/svg/card-icons/selected-usage-limit-icon.svg",
      selectedSrc: "assets/images/svg/card-icons/selected-usage-limit-icon.svg",
      icon: "usage-limit-icon",
      selectedIcon: "selected-usage-limit-icon",
    },
  ];
  static readonly cardList: Cards = [
    {
      cardName: "Moneyback Plus Visa",
      expiryDate: "4689 **** **** 6321 ",
      cardNumber: "10 Apr 2021",
      fileUrl: "assets/images/card_img1.png",
      cashLimit: "₹ 1,43,103",
      statementDate: "20 Apr 2024",
      lastPaymentDate: "09 Apr 20240",
      totalCreditLimit: "₹ 8,00,000",
      totalDueAmount: "₹ 6,55,151",
      accountCurrency: "INR",
      rewardPoint: 2150,
      dueDate: "Due on 6 June 2024",
      cardStatus: "",
      id: 0,
      bankName: "",
      customerName: "",
      validDate: "",
      typeOfCard: "",
      autoPay: false,
      currentOutStaning: 0,
      avlCreditBalance: 0,
      lastStlmtMade: 0,
      accountNumber: "",
      customerId: 0,
    },
    {
      cardName: "Moneyback Plus Visa",
      expiryDate: "4689 **** **** 6321 ",
      cardNumber: "10 Apr 2021",
      fileUrl: "assets/images/credit-card-green.png",
      cashLimit: "₹ 1,43,103",
      statementDate: "20 Apr 2024",
      lastPaymentDate: "09 Apr 20240",
      totalCreditLimit: "₹ 8,00,000",
      totalDueAmount: "",
      accountCurrency: "",
      rewardPoint: 0,
      dueDate: 0,
      cardStatus: "",
      id: 0,
      bankName: "",
      customerName: "",
      validDate: "",
      typeOfCard: "",
      autoPay: false,
      currentOutStaning: 0,
      avlCreditBalance: 0,
      lastStlmtMade: 0,
      accountNumber: "",
      customerId: 0,
    },
    {
      cardName: "Moneyback Plus Visa",
      expiryDate: "4689 **** **** 6321 ",
      cardNumber: "10 Apr 2021",
      fileUrl: "assets/images/credit-card-red.png",
      cashLimit: "₹ 1,43,103",
      statementDate: "20 Apr 2024",
      lastPaymentDate: "09 Apr 20240",
      totalCreditLimit: "₹ 8,00,000",
      totalDueAmount: "",
      accountCurrency: "",
      rewardPoint: 0,
      dueDate: 0,
      cardStatus: "",
      id: 0,
      bankName: "",
      customerName: "",
      validDate: "",
      typeOfCard: "",
      autoPay: false,
      currentOutStaning: 0,
      avlCreditBalance: 0,
      lastStlmtMade: 0,
      accountNumber: "",
      customerId: 0,
    },
    {
      cardName: "Moneyback Plus Visa",
      expiryDate: "4689 **** **** 6321 ",
      cardNumber: "10 Apr 2021",
      fileUrl: "assets/images/credit-card-red.png",
      cashLimit: "₹ 1,43,103",
      statementDate: "20 Apr 2024",
      lastPaymentDate: "09 Apr 20240",
      totalCreditLimit: "₹ 8,00,000",
      totalDueAmount: "",
      accountCurrency: "",
      rewardPoint: 0,
      dueDate: 0,
      cardStatus: "",
      id: 0,
      bankName: "",
      customerName: "",
      validDate: "",
      typeOfCard: "",
      autoPay: false,
      currentOutStaning: 0,
      avlCreditBalance: 0,
      lastStlmtMade: 0,
      accountNumber: "",
      customerId: 0,
    },
  ];
  static readonly detailsItem: HeaderModel[] = [
    {
      key: "currentOutStaning",
      label: "Current Outstanding",
      actionItem: () => "Convert to EMI",
    },
    {
      key: "avlCreditBalance",
      label: "Available Credit Limit",
      actionKey: "cashLimit",
      actionItem: (cashLimit: string) => `* Includes Cash limit ${cashLimit}`,
    },
    {
      key: "totalCreditLimit",
      label: "Total Credit Limit",
      actionItem: () => "Increase",
    },
    {
      key: "statementDate",
      label: "Statement Date",
    },
    {
      key: "lastStlmtMade",
      label: "Last Statement Made",
    },
    {
      key: "lastPaymentDate",
      label: "Last Payment Date",
    },
  ];
  static readonly recentTransTabs: string[] = ["Unbilled Transaction"];
  static readonly recentTransColumn: TableHeader[] = [
    {
      headerDef: "icustRefNo",
      headerCell: "Ref Number",
    },
    {
      headerDef: "transferType",
      headerCell: "Details",
    },
    {
      headerDef: "debitAmount",
      headerCell: "Amount",
    },
    {
      headerDef: "created",
      headerCell: "Transaction Date",
    },
  ];

  static readonly recentTransData: CardTransactionModel[] = [
    {
      date: "24 Apr",
      refNumber: "437743738732847",
      details: "UPI CC-24042024-411504615701",
      amount: "- ₹ 20,900",
      points: 60,
      transactionDate: "10 Apr 2023",
    },
    {
      date: "28 Apr",
      refNumber: "437743738732847",
      details: "UPI CC-24042024-411504615701",
      amount: "- ₹ 10,500",
      points: 30,
      transactionDate: "10 Apr 2024",
    },
  ];
  static readonly quickLinks: QuickLinkTabModel[] = [
    {
      screenName: "Service",
      childTab: this.serviceTabs,
    },
    {
      screenName: "Manage Card",
      childTab: this.manageCardTabs,
    },
    {
      screenName: "Apply",
      childTab: this.applyTabs,
    },
  ];
}
