export class PersonalDetailsConstant {
  static readonly GENERIC_SATIC_KEYS = {
    RESIDENCETYPE: [],
    GENDER: [],
    PREFIX: [],
    MARITALSTATUS: [],
    EMPLOYMENTTYPE: [],
    RELATIONSHIPTYPE: [],
    COMMUNICATIONTYPE: [],
  };
}

export enum PersonalDetailsEnum {
  RESIDENCETYPE = 'RESIDENCETYPE',
  GENDER = 'GENDER',
  PREFIX = 'PREFIX',
  MARITALSTATUS = 'MARITALSTATUS',
  EMPLOYMENTTYPE = 'EMPLOYMENTTYPE',
  RELATIONSHIPTYPE = 'RELATIONSHIPTYPE',
  COMMUNICATIONTYPE = 'COMMUNICATIONTYPE',
}
