import { TabModel } from "app/shared/models/tab-model";

export class loanServiceStore {
    static readonly serviceTabs: TabModel[] = [
        {
            screenName: "My Loan",
            route: "/loan/dashboard/dashboard",
            src: "assets/images/net-banking/loans/loan-repayment.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "view_statement",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Loan Repayment",
            route: "user/loan/loan-service/loan-repayment",
            src: "assets/images/net-banking/loans/loan-repayment.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "loan_repayment",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Top up loan",
            route: "/loan/dashboard/loan-topUP",
            src: "assets/images/net-banking/loans/topUp.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "topUP",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Repayment cycle",
            route: "/loan/loan-dashboard/repayment-cycle",
            src: "assets/images/net-banking/loans/repayment-cycle.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "payment-icon",

            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "E Statement",
            route: "/loan/loan-service/e-statement",
            src: "assets/images/net-banking/loans/e-statement.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "emi-icon",
            selectedIcon: "selected-emi-icon",
        },
        {
            screenName: "Modify Tenure",
            route: "/loan/loan-service/modify-tenure",
            src: "assets/images/net-banking/loans/modify-tenure.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "modify_tenure",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Disbursement Request",
            route: "/loan/loan-service/disbursement-request",
            src: "assets/images/net-banking/loans/disbursment-request.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "card-summary-icon",
            selectedIcon: "selected-card-summary-icon",
        },
        {
            screenName: "Disbursement Schedule",
            route: "/loan/loan-dashboard/disbursement-schedule",
            src: "assets/images/net-banking/loans/disbursment-schedule.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "autopay-icon",
            selectedIcon: "selected-autopay-icon",
        },
        {
            screenName: "Repayment Schedule",
            route: "/loan/loan-service/repayment-schedule",
            src: "assets/images/net-banking/loans/repayment-schedule.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "autopay-icon",
            selectedIcon: "selected-autopay-icon",
        },
        {
            screenName: "Pre Generated Statement",
            route: "/loan/loan-service/pre-generated-statement",
            src: "assets/images/net-banking/loans/pre-generated.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "bill-cycle-icon",
            selectedIcon: "selected-bill-cycle-icon",
        },
        {
            screenName: "View Statement",
            route: "/loan/loan-service/view-statement",
            src: "assets/images/net-banking/loans/view-statement.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "change-pin-icon",
            selectedIcon: "selected-change-pin-icon",
            skipActionButton: true,
        },
        {
            screenName: "Gold renewal",
            route: "/loan/loan-service/gold-renewal",
            src: "assets/images/net-banking/loans/gold-renewal.svg",
            selectedSrc: "assets/images/svg/loan-view-statement-icon.svg",
            icon: "change-pin-icon",
            selectedIcon: "selected-change-pin-icon",
            skipActionButton: true,
        },
        {
            screenName: "Request Certificate",
            route: "/loan/loan-service/request-certificate",
            src: "assets/images/net-banking/loans/request-certificate.svg",
            selectedSrc: "assets/images/svg/loan-request-certificate-icon.svg",
            icon: "emi-details-icon",
            selectedIcon: "selected-emi-details-icon",
        },

        {
            screenName: "Interest Statement",
            route: "/loan/loan-service/interest-statement",
            src: "assets/images/net-banking/loans/interest-statement.svg",
            selectedSrc: "assets/images/svg/loan-interest-statement-icon.svg",
            icon: "payment-icon",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Schedule Payment",
            route: "/loan/loan-service/schedule-payment",
            src: "assets/images/net-banking/loans/schedule-payment.svg",
            selectedSrc: "assets/images/svg/loan-interest-statement-icon.svg",
            icon: "payment-icon",
            selectedIcon: "selected-payment-icon",
        },
    ];
    static readonly applyTabs: TabModel[] = [
        {
            screenName: "Apply Loan",
            route: "",
            src: "assets/images/svg/apply_loan.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "payment-icon",
            selectedIcon: "selected-payment-icon",
        },
        {
            screenName: "Tracking",
            route: "",
            src: "assets/images/svg/tracking.svg",
            selectedSrc: "assets/images/svg/selected-quick-transfer.svg",
            icon: "payment-icon",
            selectedIcon: "selected-payment-icon",
        },
    ];
}
