export enum ApprvalStatusEnum {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  ONGOING = "ONGOING",
  QUERY = "QUERY",
  REVIEWED = "REVIEWED",
  CONFIRMED = "CONFIRMED",
  INITIATED = "INITIATED",
}
