export const documentResp = {
  statusCode: 200,
  status: 'OK',
  data: [
    {
      id: 133485,
      seq: 3,
      document: 'Last 6 Months Bank Statement',
      summary: 'Last 6 Months Bank Statement',
      mandatoryForNxtStg: true,
      mandatoryForApproval: false,
      docRequired: true,
      noOfDocumentToUpload: 1,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: [
        {
          id: 7202,
          uuid: 'd8db0cea-da47-49ce-8f69-d9fe7f068942',
          renamedFileName:
            'd8db0cea-da47-49ce-8f69-d9fe7f068942-20250819T111515357.pdf',
          timeStamp: null,
          fileSize: null,
          documentType: 'National Id',
          fileName: 'Acct Statement_XX4429_16052024.pdf',
          fileType: 'application/pdf',
          documentSide: 1,
          verificationType: 'kyc',
          fileUrl:
            'd8db0cea-da47-49ce-8f69-d9fe7f068942-20250819T111515357.pdf',
          documentNumber: '',
          issueDate: null,
          expiryDate: null,
          dob: null,
          phoneNumber: null,
          documentDesc: null,
          documentNameForChecklist: 'Last 6 Months Bank Statement',
          countryOfIssue: null,
          documentName: null,
          documentId: null,
          signatureId: null,
          primary: false,
          proofOfAddress: false,
        },
      ],
      originationId: 4063,
    },
    {
      id: 200003,
      seq: 5,
      document: 'Registration Certificate',
      summary: 'Registration Certificate',
      mandatoryForNxtStg: true,
      mandatoryForApproval: false,
      docRequired: true,
      noOfDocumentToUpload: null,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: [
        {
          id: 7203,
          uuid: 'ba8c2cd4-bf3d-4d61-8577-dae4feedb149',
          renamedFileName:
            'ba8c2cd4-bf3d-4d61-8577-dae4feedb149-20250819T111530943.pdf',
          timeStamp: null,
          fileSize: null,
          documentType: 'National Id',
          fileName: 'registration certificate.pdf',
          fileType: 'application/pdf',
          documentSide: 1,
          verificationType: 'kyc',
          fileUrl:
            'ba8c2cd4-bf3d-4d61-8577-dae4feedb149-20250819T111530943.pdf',
          documentNumber: '',
          issueDate: null,
          expiryDate: null,
          dob: null,
          phoneNumber: null,
          documentDesc: null,
          documentNameForChecklist: 'Registration Certificate',
          countryOfIssue: null,
          documentName: null,
          documentId: null,
          signatureId: null,
          primary: false,
          proofOfAddress: false,
        },
      ],
      originationId: 4063,
    },
    {
      id: 133488,
      seq: 6,
      document: 'Collateral',
      summary: 'Collateral',
      mandatoryForNxtStg: false,
      mandatoryForApproval: false,
      docRequired: false,
      noOfDocumentToUpload: null,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: null,
      originationId: 4063,
    },
    {
      id: 200004,
      seq: 4,
      document: 'Incorporation Certificate',
      summary: 'Incorporation Certificate',
      mandatoryForNxtStg: true,
      mandatoryForApproval: false,
      docRequired: true,
      noOfDocumentToUpload: 2,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: [
        {
          id: 7204,
          uuid: '9cfe0355-cac7-4c59-9ea8-1192e2fe25ab',
          renamedFileName:
            '9cfe0355-cac7-4c59-9ea8-1192e2fe25ab-20250819T111541898.pdf',
          timeStamp: null,
          fileSize: null,
          documentType: 'National Id',
          fileName: 'incorporate certificate.pdf',
          fileType: 'application/pdf',
          documentSide: 1,
          verificationType: 'kyc',
          fileUrl:
            '9cfe0355-cac7-4c59-9ea8-1192e2fe25ab-20250819T111541898.pdf',
          documentNumber: '',
          issueDate: null,
          expiryDate: null,
          dob: null,
          phoneNumber: null,
          documentDesc: null,
          documentNameForChecklist: 'Incorporation Certificate',
          countryOfIssue: null,
          documentName: null,
          documentId: null,
          signatureId: null,
          primary: false,
          proofOfAddress: false,
        },
        {
          id: 7205,
          uuid: '199d186f-6ce4-4ba9-ae52-8568df609aef',
          renamedFileName:
            '199d186f-6ce4-4ba9-ae52-8568df609aef-20250819T111559942.jpeg',
          timeStamp: null,
          fileSize: null,
          documentType: 'National Id',
          fileName: 'Incorporation.jpeg',
          fileType: 'image/jpeg',
          documentSide: 2,
          verificationType: 'kyc',
          fileUrl:
            '199d186f-6ce4-4ba9-ae52-8568df609aef-20250819T111559942.jpeg',
          documentNumber: '',
          issueDate: null,
          expiryDate: null,
          dob: null,
          phoneNumber: null,
          documentDesc: null,
          documentNameForChecklist: 'Incorporation Certificate',
          countryOfIssue: null,
          documentName: null,
          documentId: null,
          signatureId: null,
          primary: false,
          proofOfAddress: false,
        },
      ],
      originationId: 4063,
    },
    {
      id: 133484,
      seq: 2,
      document: 'Balance Sheet',
      summary: 'Balance Sheet',
      mandatoryForNxtStg: true,
      mandatoryForApproval: false,
      docRequired: false,
      noOfDocumentToUpload: null,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: null,
      originationId: 4063,
    },
    {
      id: 200006,
      seq: 8,
      document: 'GST Registration Certificate',
      summary: 'GST Registration Certificate',
      mandatoryForNxtStg: false,
      mandatoryForApproval: false,
      docRequired: false,
      noOfDocumentToUpload: null,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: null,
      originationId: 4063,
    },
    {
      id: 200005,
      seq: 7,
      document: 'Income Tax Returns',
      summary: 'Income Tax Returns',
      mandatoryForNxtStg: false,
      mandatoryForApproval: false,
      docRequired: false,
      noOfDocumentToUpload: null,
      documentTypes: [],
      documentTypesValue: [],
      docInfoModel: null,
      originationId: 4063,
    },
  ],
  message: 'Data fetched successfully',
};
